/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package baru;

import org.junit.jupiter.api.Test;

import app.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
